# Part 1
## Describe the historical context of the digital economy
At this time it is difficult to realize where we at in terms of Digital Economy, this because the pandemic change lots of aspects of our lives, there where some practices that were not upgraded because there was no need to upgrade, many industries such as banking industries were moving forwards to bet in digital transformation, despite this, the pandemic carry new challenges to solve and many policies that needed to be implemented and dig out in order to provide the best service possible and to help to other industries to keep up with their own activities, making applications powered by security and innovative approaches. 

## Describe the use of information technology in economic crises
We believe that there are many aspects of the nowadays system that have contribute to the actual economic crisis, some of the different sources aims that a big part of the problems that we are facing right now is the capitalism, to be able to monetize every part of a process is one of the most incredible features of it, nevertheless, the great gap in this process is that the people how own most of the money that the monetization come from does not spend it in the right areas, because as much as they generates, the debt increase directly proportional, by reading some books there is a new concept that has a direct relation with the use of the information technology and were it merges with the economic crisis and it is the concept of data capitalism. 

Data capitalism have two different approaches, in the first one it propose that there is a segmentation of the population that is not being taking into account, because the engage that is making is focus on the population that reserves all the privileges to them, with this point it merges with the part of the monetization of the data, which is also part of the data capitalism, where the box of debts is increasing as much as the box of money that enterprises have increases and there is no balance to make sure that money is reaching the right purpose. 

## Describe Industry 4.0 and priors (e.g., the information economy)
For describing the industry 4.0, it is extremely necessary to understand the prior industries, and which elements were the ones that took place to make an industrial revolution, and its characteristics. It is also important to know the economic features of the different stages of the history and how the revolution change the economy with the optimization or processes and the impact on daily life.

The 1st industrial revolution took place in Great Britain, where the steam machine, and the railway were the main components of this industrial revolution, in terms of economy, what make the economy growth was the help of machines to have the mobility to have an open market with different places and provide exchange at any stage. The 2nd industrial revolution, was where the economic model that we are following right now took part, because the capitalism was born at this moment, where the enterprises had a lot of resources, and with the help of the machinery the manufacturing cost where lower, with this a lot of people were unemployed but there were new economic powers such as Japan, Germany, or USA, it is important to mention that the electricity was also one of the most important discoveries in the SIR, and the fuel for the machinery was electricity, making it a highly rentable energy. Then the 3rd revolution where the principal fuel was also electricity, was the one where the automation took part, informatics, with the development of the internet where the main authors of the third revolution, in terms of economy it helped, because new employments emerged, creating new job positions at different levels making an important reduce on the index of unemployment. Finally, the 4th revolution is the one that is shaping right now, at this moment we can see the development of industries like IoT and Information as the main resource of money, with disruptive concurrencies in transit, besides that the cloud technologies have been boosters for a quick development of all these different technologies. In this revolution we also see an increase in the work proposals, and new ways of making money that before were not possible. Despite this we are still struggling because of the different benefits that have been ripped from every job. In the next module we will talk more about it. 

## Describe the next revolution in production.
In terms of economy, we believe that we should not expect more formal employment, this because every time there are more tasks that can be automated thanks to the cloud and the software that is being released every year, nevertheless all these features have evolved to not just be for big enterprises, but to small ones who are looking forwards an increase on their different areas of opportunity, and be accessible to a larger amount of population. Another important aspect about the economy are the cryptos, which have been something difficult to read, being one of the best options to invest though. The technology from labs will reach other industries such as the health industries, or the automotive industry, and reaching the homes of population like the case of home automation. 

In terms of education, for 4th industry has also been an important aspect to talk about whenever we want to highlight the benefits that this 4th industry has support. And to sum up, the pandemic forced many different enterprises to begin the digitalization of their business to be more productive. We hope that the challenges that are needed to be solved are accomplished, and that no power let the technology evolve.  
 





